### ISSUE TITLE
How can i move multitenant applications to cloud fiori launchpad

### ISSUE THREAD

**Issue by chandeep2013** [saphanaacademy/SAPHANAAcademy#7]
Hello,

Can you help me to push multitenant apps to the cloud Fiori launchpad?

Regards,
Chamdeep

**Comment by saphanaacademy** [comment]
Hi @chandeep2013 

Please use the [SAP Community](https://answers.sap.com) for general Q&A. There is a [BTP](https://answers.sap.com/tags/8077228b-f0b1-4176-ad1b-61a78d61a847) tag:

Thanks,
SAP HANA Academy
