### ISSUE TITLE
Project Deployment failed After updating generator-saphanaacademy-saas for new projects

### ISSUE THREAD

**Issue by chandeep2013** [saphanaacademy/SAPHANAAcademy#8]
Hello,

Yesterday I have updated "**generator-saphanaacademy-saas**". After updating, I tried to create a new project and tried to deploy with generated code without any changes. 

**Error:** Error staging application "cflapservice": BuildpackCompileFailed - App staging failed in the buildpack compile phase
Download the application logs via the dmol command and check them for more information.
A step of the process has failed. Retrying it may solve the issue.

Since yesterday I am getting below errors.
In logs, I can see the below errors. 

npm ERR! errno ENOTFOUND (STDOUT, STG)#
npm ERR! syscall getaddrinfo (STDOUT, STG)#
npm ERR! code ENOTFOUND (STDOUT, STG)#
npm ERR! network (STDOUT, STG)#
npm ERR! network In most cases you are behind a proxy or have bad network settings. (STDOUT, STG)#
npm ERR! network This is a problem related to network connectivity. (STDOUT, STG)#
npm ERR! network request to http://nginx-redirector.repo-cache.svc.cluster.local/repository/appstudio-npm-group/@sap/audit-logging/-/audit-logging-5.5.4.tgz failed, reason: getaddrinfo ENOTFOUND nginx-redirector.repo-cache.svc.cluster.local (STDOUT, STG)#
npm ERR! network 'proxy' config is set properly.  See: 'npm help config' (STDOUT, STG)#
npm ERR! network If you are behind a proxy, please make sure that the (STDOUT, STG)#
Failed to compile droplet: Failed to run all supply scripts: exit status 14 (STDERR, STG)#

Please let me know what can I do to fix this problem from my end. I am attaching the logs below.

[cflapservice.log](https://github.com/saphanaacademy/SAPHANAAcademy/files/9007199/cflapservice.log)

Regards,
Chamdeep

**Comment by saphanaacademy** [comment]
Hello,

Your issue relates to the way SAP Business Application Studio caches the npm packages. generator-saphanaacademy-saas has been updated to try to work around this. Please install the latest release (0.0.13) and re-generate your project.

If you continue to experience this type of issue please see the "best answer" to this [SAP Community question](https://answers.sap.com/questions/13544661/how-to-avoid-changes-in-package-lockjson-when-usin.html). i.e. add a .npmrc file containing `registry=https://registry.npmjs.com/` to each folder of your project with a package.json, remove all package-lock.json files then re-build and deploy.

Thanks,
Philip
